ecommerce2/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from products import views
from carts import views as cart_views
from orders import views as order_views
from accounts import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('s/',views.search, name='search'),
    path('products/',views.all, name='products'),
    path('cart/',cart_views.view, name='cart'),
    path('checkout/',order_views.checkout, name='checkout'),
    path('orders/',order_views.orders, name='user_orders'),
    #path('^products/(?P<slug>.*)/$',views.single, name='single_product'),
    re_path(r'^products/(?P<slug>[\w-]+)/$', views.single, name='single_product'),
    re_path(r'^cart/(?P<id>\d+)/$', cart_views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^cart/(?P<slug>[\w-]+)/$', cart_views.add_to_cart, name='add_to_cart'),

    
    path('accounts/logout/', account_views.logout_view , name='auth_logout' ),
    path('accounts/login/', account_views.login_view , name='auth_login' ),
    path('accounts/register/', account_views.registration_view , name='auth_register' ),

    re_path(r'^accounts/activate/(?P<activation_key>\w+)/$', account_views.activation_view , name='activation_view'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	price = models.DecimalField(decimal_places=2, max_digits=100, default=20.99)
	sale_price = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
	slug = models.SlugField(unique=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	
	def __str__(self):
		return self.title

	class Meta:
		unique_together = ('title', 'slug')

	def get_price(self):
		return self.price

	def get_absolute_url(self):
		return reverse("single_product", kwargs={"slug": self.slug})


class ProductImage(models.Model):
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	image = models.ImageField(upload_to='products/images')
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.product.title


class VariationManager(models.Manager):

	def all(self):
		return super(VariationManager, self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size')
	
	def colors(self):
		return self.all().filter(category='color')


VAR_CATEGORIES = (
	('size','size'),
	('color', 'color'),
	('package', 'package')

)

class Variation(models.Model):
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
	title = models.CharField(max_length=120)
	image = models.ForeignKey(ProductImage,on_delete=models.CASCADE, null=True, blank=True)
	price = models.DecimalField(decimal_places=2, max_digits=100,null=True, blank=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	objects = VariationManager()

	def __str__(self):
		return self.title

products/views.py
from django.shortcuts import render,Http404
from .models import Product, ProductImage
# Create your views here.
from marketing.models import MarketingMessage

def search(request):
	try:
		q = request.GET.get('q')
	except:
		q=none
	if q:
		products = Product.objects.filter(title__icontains=q)
		context = {'query':q, 'products': products }
		template = 'products/results.html'
	else:
		template='products/home.html'
		context={}
	return render(request, template, context)

def home(request):
	products = Product.objects.all()
	marketing_message = MarketingMessage.objects.all()[0]
	template = 'products/home.html'
	context = {"products": products}
	return render(request, template, context)


def all(request):
	products=Product.objects.all()
	context = {'products':products}
	template='products/all.html'
	return render(request, template, context)

def single(request, slug):
	try:
		product = Product.objects.get(slug=slug)
		#images = product.productimage_set.all()
		images = ProductImage.objects.filter(product=product)
		context = {'product':product, "images": images}
		template='products/single.html'
		return render(request, template, context)
	except:
		raise Http404

templates/products/all.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %} Products {% endblock %}


 {% block styles %}
 	.jumbotron{
 		color: red;
 	}

 {% endblock %}



{% block content %}

{% load static %}

<div class = 'row'>
	{% for product in products %}
<div class ='col-sm-2'>

	<div class="thumbnail" style="border: 2px solid #C0C0C0;padding: 5px;">
		{% if product.productimage_set.all %}
			{% for item in  product.productimage_set.all %}
				{% if item.featured %}

					<div style="width:100px;
					height:100px;margin: 0 auto;">
					<a href="{{ product.get_absolute_url }}">
					<div class="background_img_thumb" style="width:80%; height:80%;
					background-image: url('/media/{{ MEDIA_ROOT}}{{ item.image }}');"></div>
					</a>
					</div>

					<!-- <img class='img-responsive' src="/media/{{ MEDIA_ROOT}}{{ item.image }}"/> -->
				{% endif %}
			{% endfor %}
		{% else %}

		<!-- <img class='img-responsive' src="{% static 'img/unnamed.jpg' %}" width="80" height="80"/> -->

		<div style="width:100px;
					height:100px;margin: 0 auto;">
					<a href="{{ product.get_absolute_url }}">
					<div class="background_img_thumb" style="width:80%; height:80%;
					background-image:src='{% static 'img/unnamed.jpg' %}';"></div>
					</a>
		</div>

		{% endif %}

		 <div class="caption">
			 <a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
			 <p>{{ product.description|truncatewords:15 }}</p>
			 <p> <a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button" >Button</a> </p>
			</div>
		</div>
	</div>
	{% cycle "" "" "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}
</div>


{% endblock %}

templates/products/home.html
{% extends "base.html" %}

{% load static %}

{% block heat_titel %} Welcome {% endblock %}


 {% block styles %}
 	.jumbotron{
 		color: red;
 	}

 {% endblock %}

{% block jumbotro2 %}
<div class ="container">
<div class="jumbotron">
    <h1>Navbar example</h1>
    <p class="lead">This example is a quick exercise to illustrate how fixed to top navbar works. As you scroll, it will remain fixed to the top of your browser’s viewport.</p>
    <a class="btn btn-lg btn-primary" href="/docs/4.4/components/navbar/" role="button">View navbar docs &raquo;</a>
 </div>
</div>
{% endblock %}



{% block content %}

{% load static %}

<div class = 'row'>
	{% for product in products %}
<div class ='col-sm-4'>

	<div class="thumbnail" style="border: 2px solid #C0C0C0;padding: 5px;">
		{% if product.productimage_set.all %}
			{% for item in  product.productimage_set.all %}
				{% if item.featured %}

					<div style="width:150px;
					height:160px;margin: 0 auto;">
					<a href="{{ product.get_absolute_url }}">
					<div class="background_img_thumb" style="width:100%; height:100%;
					background-image: url('/media/{{ MEDIA_ROOT}}{{ item.image }}');"></div>
					</a>
					</div>

					<!-- <img class='img-responsive' src="/media/{{ MEDIA_ROOT}}{{ item.image }}"/> -->
				{% endif %}
			{% endfor %}
		{% else %}
		<!-- <img class='img-responsive' src="{% static 'img/unnamed.jpg' %}" width="80" height="80"/> -->

		<div style="width:150px;
					height:160px;margin: 0 auto;">
					<a href="{{ product.get_absolute_url }}">
					<div class="background_img_thumb" style="width:100%; height:100%;
					background-image: src='{% static 'img/unnamed.jpg' %}';"></div>
					</a>
		</div>
		{% endif %}

		 <div class="caption">
			 <a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
			 <p>{{ product.description|truncatewords:15 }}</p>
			 <p> <a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button" >Button</a> </p>
			</div>
		</div>
	</div>
	{% cycle "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}
</div>


{% endblock %}

templates/products/results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1> Searched for: {{ query }} </h1>

{{ products }}

<table class="table">
<thead>
	<th></th>
	<th>Product</th>
</thead>

<tbody>
{% for product in products %}
	<tr>
		<td style="width:160px; 
		height:160px;
		background-image:">
		{% if product.productimage_set.all %}
			{% for item in  product.productimage_set.all %}
				{% if item.featured %}
				
<!-- 				<div style="width:100%; height:100%;
				background-image: url('/media/{{ MEDIA_ROOT}}{{ item.image }}');
				background-size:cover;
				background-repeat:no-repeat;
				background-position: center ">
				</div> -->
				<a href="{{ product.get_absolute_url }}">
				<div class="background_img_thumb" style="width:100%; height:100%;
				background-image: url('/media/{{ MEDIA_ROOT}}{{ item.image }}');">
				</div>
				</a>

				{% endif %}
			{% endfor %}

		{% else %}
		<a href="{{ product.get_absolute_url }}">
		<div class="background_img_thumb"></div>
		</a>
<!-- 		<div style="width:100%; height:100%;
		background-image:url('{% static 'img/unnamed.jpg' %}'); 
		background-size:cover; 
		background-repeat:no-repeat;
		background-position: center; "> -->
		</div>
		{% endif %}
		</td>
		<td>
		<a href="{{ product.get_absolute_url }}">
		{{product}}
		</a>
		</td> 
	</tr>
{% endfor %}
</tbody>

</table>

{% endblock %}

templates/products/single.html
{% extends 'base.html' %}

<div class="page-header">
  <h1>{{ product.title }}</h1>
</div>

{% block content %}


<div class='row'>
	<div class='col-sm-4'>
	{% for img in images %}
		{% if img.featured %}
			<div class="col-xs-12">
			<img class='img-responsive' src="/media/{{ MEDIA_ROOT}}{{ img.image }} " width="120" height="120"/>
			<hr/>
			</div>
		{% endif %}
		{% endfor %}

	{% for img in images %}
		{% if not img.featured %}
			<div class="col-xs-6">
			<a href="#" class="thumbnail">
			<img class='img-responsive' src="/media/{{ MEDIA_ROOT}}{{ img.image }}" width="120" height="120" />
			</a>
			</div>
		{% endif %}
	{% endfor %}
	</div>
	<div class="col-sm-8 ">
		<div class="col-sm-8 pull-left">
			<h1>{{ product.title }}</h1>
		</div>
		<div class="col-sm-4 pull-right">
			<form class='form' method="POST" action="{% url 'add_to_cart' product.slug %}">{% csrf_token %}
				<input class="btn btn-secondary btn-block " type="submit" value="Add to cart"/>
				<input class="form-control" name="qty" type ='number' value="1" />

				{% if product.variation_set.all %}

				{% if product.variation_set.sizes %}
				<select class="form-control" name='size'>
				{% for item in product.variation_set.sizes %}
					<option value='{{ item.id }}'> {{ item.title|capfirst }} </option>
					{% endfor %}
				</select>
				{% endif %}

				{% if product.variation_set.colors %}
				<select class="form-control" name='color'>
				{% for item in product.variation_set.colors %}
					<option value='{{ item.id }}'> {{ item.title|capfirst }} </option>
				{% endfor %}
				</select>
				{% endif %}

				{% endif %}

			</form>
		</div>
		<div class="col-sm-12">
			<hr/>
				Price: {{ product.price }} <br/>
				Shipping: Free with $25+ purchase.
			<hr/>
		</div>
		<div class="col-sm-12">
			{{ product.description|linebreaks }}
		</div>
	</div>

</div>
{% endblock %}